/* eslint-disable @next/next/no-css-tags */
import { Inter } from "next/font/google";
import "./globals.css";
import "./style.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next JS 14 Tutorial",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    {/* <head>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
    </head> */}
    {/* <head>
      <script src="/feature.js" async />
    </head> */}
    {/* <head>
      <link rel="stylesheet" href="/style.css" />
      <script src="/script.js" async />
    </head>  */}
      <body className={inter.className}>
      {children}</body>
    </html>
  );
}
